services:
  app:
    #build: .
    image: tojurnru/poe-youtube-post-to-discord:latest
    command: yarn start
    env_file: .env
    volumes:
      - /your-local-path/poe-youtube-post-to-discord/data:/app/data